owner: Howielyn
repo: status-monitor

sites:
  - name: Google
    url: https://www.google.com
  - name: Mozilla Archive
    url: https://archive.mozilla.org/
  - name: Amazon Music
    url: https://music.amazon.com
  - name: Web Archive 
    url: https://web.archive.org/
status-website:
  theme: dark
  css: "nav { display: none }"
  favicon: 
  faviconSvg: 
  baseUrl: /status-monitor
  logoUrl: 
  name: status-monitor

i18n:
  footer: Powered by Upptime.
